### ISSUE TITLE
[Web] Update contact email to something relevant

### ISSUE THREAD

**Issue by avilanicolas** [avilanicolas/MeleeAuthority#13]

**Comment by Matthew-Stewart** [comment]
Fixed. Will be pulled to master with next merge

**Comment by Matthew-Stewart** [comment]
( set to melee@meleeauthority.com ). Can reopen if we want to change to something else

**Comment by avilanicolas** [comment]
This is actually my mistake and I forgot to alert you to this, but I haven't set up any emails for the domain yet. For now, it would be easiest to just list peoples' personal email. I am fine with putting mine down. Later on (maybe past Friday) I'll actually make an email and put it there myself.
